@startuml

title Deployment process

start
if (no uncomitted changes to src/data.js?) then (start build)
  :compile application and output to dist/;
  :copy images to dist directory;
  repeat :for each pixel art entry;
    :generate HTML page 
    with preview and bundle.js;
  repeat while (more images?) is (repeat)
  :generate RSS feed using latest entries;
  :push dist/ to remote gh-pages branch;
else (exit)
endif

stop

@enduml
