@startuml

title Deployment process

start
if (no uncomitted changes in src/data/?) then (start build)
  :compile frontend code to dist/main.js;
  :compile build scripts for other artifacts;
  :copy images to dist/;
  repeat
    :generate page for entry;
  repeat while (has more images?) is (Yes)
  :generate dist/feed.xml;
  :push dist/ to remote gh-pages branch;
else (exit)
endif

stop

@enduml
