name: CI - Test frontend
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm i
      - name: Test
        run: npm test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Run integration tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npx http-server dist/ --silent
          wait-on: "http://localhost:8080"
