name: CI - Test frontend
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Build frontend
        run: yarn build
      - name: Run integration tests
        uses: cypress-io/github-action@v4
        with:
          start: npx http-server dist/
